[package]
name = "datafusion-object"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "6.0.0"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "sync"] }
